import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./redux/provider";
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Farm Easy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {                  
  children: React.ReactNode;
}) {                
  return (          
    <html lang="en">
        <body className={inter.className}><Providers>{children}</Providers></body>
    </html>          
  );
}
